version: '3'

services:
  terratoken-app:
    image: your-dockerhub-username/terratoken-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALCHEMY_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/T0qIBsLD5-rVNXm-gJ-dEF1J8ayyVQMM
      - CARBON_CREDIT_ADDRESS=0xE9C9495bd6a5e121a3Ce6980E8d994Ca5eD7D33C
      - VERIFICATION_ADDRESS=0xe3750E5a35BF962E0771f56f44c78F024754ce37
    restart: always
